config/routes.rb
    get "/destinations/:id/traveller_images" => "destinations#traveller_images"
    get "/destinations/:slug" => "destinations#show"
    patch "/destinations/:id" => "destinations#update"
    put "/destinations/:id" => "destinations#update"
    delete "/destinations/:id" => "destinations#destroy"
    get "/destinations-by-country" => "destinations#country_wise_destinations"

    get "/destinations/:slug/hotels" => "hotels#index"
    post  "/destinations/:destination_id/:destination_name/hotels" => "hotels#create"
    get "/destinations/:destination_id/:destination_name/hotels/new" => "hotels#new"
    get "/destinations/:destination_id/:destination_name/hotels/:id/edit"  => "hotels#edit"
    get "/destinations/:destination_id/:destination_name/hotels/:id/:name" => "hotels#show"
    put "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"
    delete  "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#destroy"
    patch "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"

    get "/destinations/:slug/flights" => "flights#index"
    post  "/destinations/:destination_id/:destination_name/flights" => "flights#create"
    get "/destinations/:destination_id/:destination_name/flights/new" => "flights#new"
    get "/destinations/:destination_id/:destination_name/flights/:id/edit"  => "flights#edit"
    get "/destinations/:destination_id/:destination_name/flights/:id/:name" => "flights#show"
    put "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"
    delete  "/destinations/:destination_id/:destination_name/flights/:id" => "flights#destroy"
    patch "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"

    get "/attractions/:slug" => "attractions#index"
    get "/attractions/:destination_slug/:attraction_slug" => "attractions#show"
    post  "/destinations/:destination_id/:destination_name/attractions" => "attractions#create"
    get "/destinations/:destination_id/:destination_name/attractions/new" => "attractions#new"
    get "/destinations/:destination_id/:destination_name/attractions/:id/edit"  => "attractions#edit"
    get "/destinations/:destination_id/:destination_name/attractions/:id/:name" => "attractions#show"
    put "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"
    delete  "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#destroy"
    patch "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"

    get "/events/:slug" => "events#index"
    get "/events/:destination_slug/:event_slug" => "events#show"
    post  "/destinations/:destination_id/:destination_name/events" => "events#create"
    get "/destinations/:destination_id/:destination_name/events/new" => "events#new"
    get "/destinations/:destination_id/:destination_name/events/:id/edit"  => "events#edit"
    get "/destinations/:destination_id/:destination_name/events/:id/:name" => "events#show"
    put "/destinations/:destination_id/:destination_name/events/:id" => "events#update"
    delete  "/destinations/:destination_id/:destination_name/events/:id" => "events#destroy"
    patch "/destinations/:destination_id/:destination_name/events/:id" => "events#update"

    get "/all-users" => "customers#all_users"
    get "/meet-travelers" => "customers#meet_travellers"
    post 'travelers/search' => "customers#search_traveler"
    post '/validate_username' => "customers#validate_username"
    
    get "/traveler/:username" => "customers#traveler"
    get "/traveler/:username/travel_blogs" => "travel_blogs#index"
    get "back_to_blog_comment/:id" => "blog_comments#back_to_comment"
    get "reply_to_comment/:id" => "blog_comments#reply_to_comment"
    root 'home#index'
    get "/get_cities" => "destinations#cities_per_country"
    get "/get_states" => "destinations#states_per_country"
    get "/hotels" => "hotels#all_index"
    get "/flights" => "flights#all_index"
    get "/events" => "events#all_index"
    get "/attractions" => "attractions#all_index"
    get "/search" => "home#search"
    get "/blog_categories" => "travel_blogs#get_categorized_data"
    get "/blog" => "travel_blogs#all_index"
    get "/blog_main" => "travel_blogs#blog_main"
    get "/blog/post/:id" => "travel_blogs#single_post"
    get "/blog/new" => "travel_blogs#new_post"
    post "/blog/new" => "travel_blogs#create_post"
    get "/blog/edit/:id" => "travel_blogs#edit_post"
    delete "/blog/delete/:id" => "travel_blogs#destroy"
    post "/blog/edit/:id" => "travel_blogs#update_post"
    post "blog/post/:id/comment" => "blog_comments#create"
    get "dynamic_js_content.:ext" => "home#dynamic_content"
    get "/filter-destinations" => "destinations#filter_destinations"
    get "contact" => "home#contact"
    get "faq" => "home#faq"
    get "contribute" => "home#contribute"
    get "advertise" => "home#advertise"
    get "privacy" => "home#privacy"
    get "careers" => "home#careers"
    get "terms" => "home#terms"
    get "partner_with_us" => "home#partner_with_us"
    post "contact" => "home#contact_form"
    get "/about" => "home#about"
    get "/add-listing" => "home#add_listing"
    post "/add-listing" => "home#save_listing"
    get "/report-spam" => "home#report_spam"
    post "/report-spam" => "home#save_spam"
    get "/report-fraud" => "home#report_fraud"
    post "/report-fraud" => "home#save_fraud"
    post "about" => "home#about"
    post "/share-as-email" => "home#share_as_email"
    get 'wishlists/add' => "wishlists#create"
    get '/customers/:customer_id/wishlists' => "wishlists#index"
    get 'recommendations/add' => "recommendations#create"
    get '/customers/:customer_id/recommendations' => "recommendations#index"
    get '/customers/:customer_id/posts' => "customers#posts"
    post '/posts/:id/comment' => "customers#comment"
    get '/posts/:id/show' => "customers#show_post"
    get '/posts/:id/edit' => "customers#edit_post"
    post '/posts/:id/update' => "customers#update_post"
    get '/posts/:id/like' => "customers#like"
    get '/posts/:id/remove' => "customers#remove_post"
    get '/customers/:customer_id/gallery' => "customers#gallery"
    get '/customers/:customer_id/gallery/:country' => "customers#gallery_by_country"
    get '/customers/:customer_id/followings' => "customers#followings"
    get '/customers/:customer_id/followers' => "customers#followers"
    get "customers/accept_as_public_traveller" => "customers#update_visibility"
    get "/customers/create-post" => "customers#create_post"
    post "/customers/create-post" => "customers#save_post"
    get "/recommendation" => "customers#recommendation"
    get '/wishlists/auth' => "wishlists#index"
    get '/checkins/auth' => "checkins#index"
    get '/recommendation/auth' => "recommendations#index"
    delete 'customers/:customer_id/wishlists/:id' => "wishlists#destroy"
    delete 'customers/:customer_id/recommendations/:id' => "recommendations#destroy"
    get 'checkins/add' => "checkins#create"
    get 'customers/:customer_id/checkins' => "checkins#index"
    delete 'customers/:customer_id/checkins/:id' => "checkins#destroy"
    get '/terms' => "admins#terms"
    get '/faq' => "admins#faq"
    get '/careers' => "admins#careers"
    get '/privacy' => "admins#privacy"
    get '/about' => "admins#about_us"
    get '/terms/edit' => "admins#edit_terms"
    get '/faq/edit' => "admins#edit_faq"
    get '/careers/edit' => "admins#edit_careers"
    get '/privacy/edit' => "admins#edit_privacy"
    get '/about/edit' => "admins#edit_about_us"
    post '/terms/edit' => "admins#update_terms"
    post '/faq/edit' => "admins#update_faq"
    post '/careers/edit' => "admins#update_careers"
    post '/privacy/edit' => "admins#update_privacy"
    post '/about/edit' => "admins#update_about_us"
    get "/change-status" => "customers#change_status"
    post "/change-status" => "customers#update_status"

    resources :destinations do
      get "traveller_images"
      resources :flights do
        resources :flight_facilities
      end
      resources :hotels do
        resource :hotel_facilities
        resource :mores
      end
      resources :attractions
      resources :events
    end

    patch "/update_d_rating/:id" => "ratings#update_destination"
    patch "update_f_rating/:id" => "ratings#update_flight"
    patch "update_h_rating/:id" => "ratings#update_hotel"
    post "/destinations/:id/uploads/create" => "destinations#upload_create"

    get "/add_flights" => "flights#new"
    get "/add_hotels" => "hotels#new"
    get "/add_events" => "events#new"
    get "/add_attractions" => "attractions#new"
    get "/forums" => "forum#index"
    get "/forum/:region" => "topics#index"
    get "/forum/:id/additional" => "topics#additional_index"
    get "/forum/:id/topics/:topic_id" => "topics#additional_show"
    get "/forum/country/:country_name" => "forum#country"
    scope "/forum" do
      resources :topics do
        resources :post_topics
      end
    end

    resources :customers, :only => [:show] do
      resources :trips
      resources :photos
      resources :travel_blogs do 
        resources :blog_comments
      end
      get "friends" => "customers#friends"
      get "add-friend" => "customers#add_users"
      get "follow" => "customers#follow"
      get "unfollow" => "customers#unfollow"
      get "edit_profile" => "profiles#edit"
      post "edit_profile" => "profiles#update"
      post  "edit_image"  =>  "profiles#update_profile_image"
      post "disconnect-users/:id" => "customers#disconnect_users"
      get "profile" => "profiles#show"
      get "collections" => "customers#collections"
      get "likes" => "customers#likes"
      get "reviews" => "customers#reviews"
    end
    get "/notifications" => "customers#notifications"

    resources :conversations, only: [:index, :create] do
      resources :messages, only: [:index, :create]
    end
    
  end
  

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :post_topics
  belongs_to :customer


  def self.filter_topics(type)
    if type["sortby"] == AppConstants::SORT_BY_COUNTRY_FOR_TOPIC.to_s
      topic = Topic.includes(:customer, :post_topics).where(:location_country=>type["sort_by_country"])
    elsif type["sortby"] == AppConstants::SORT_BY_STATE_FOR_TOPIC.to_s
      topic = Topic.includes(:customer, :post_topics).where(:location_state=>type["sort_by_country"])
    elsif type["sortby"] == AppConstants::SORT_BY_CITY_FOR_TOPIC.to_s
      topic = Topic.includes(:customer, :post_topics).where(:location_city=>type["sort_by_country"])
    end
    topic
  end

  def self.search_topic_by_country
    topics = Topic.all
    country_data_hash = Hash.new
    AppUtils.get_regions_by_country_code.each do |country|
      country_data_hash[country[1]] = Array.new
      topics.each do |topic|
        if topic.location_country == country[1]
          country_data_hash[country[1]] << topic
        end
      end
    end
    country_data_hash
  end

  def self.get_view_count(country_obj)
    data_obj = 0
    country_obj.each do |data|
      data_obj += data.view_count
    end
    data_obj
  end

  def self.get_view_region(data_obj)
    region_hash = Hash.new
    AppUtils.get_regions_by_country_code.each do |region|
      region_hash[region[2]] = Array.new unless region_hash.key?(region[2])
      region_hash[region[2]] << data_obj[region[1]] if data_obj[region[1]].present?
    end
    region_hash
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_customer!, :except=> [:show, :index]

  def index
    if params["sortby"].present?
      @topics = Topic.filter_topics(params)
    else
      @topics_by_country = Topic.search_topic_by_country
      @topics = Topic.includes(:customer, :post_topics).all
    end
    add_breadcrumb "Forum", "/forum"
    add_breadcrumb "#{AppConstants::REGIONS_HASH[params[:region].to_i]}", "#{params[:region]}"
    render layout: "v2"
  end

  def additional_index
    @topics = Topic.includes(:post_topics, :customer).where("additional_topic = (?)", params[:id].to_i).paginate(page: params[:page], per_page: 10)
    render layout: "v2"
  end

  def additional_show
    @topic = Topic.includes(:post_topics, :customer).find(params[:topic_id].to_i)
    @post_topics = @topic.post_topics.paginate(page: params[:page], per_page: 10)
    AppUtils.view_counter(@topic)
  end

  def show
    @post_topics = @topic.post_topics.paginate(page: params[:page], per_page: 10)
    AppUtils.view_counter(@topic)
    add_breadcrumb "Forum", "/forum"
    country_name = AppUtils.country_name_by_country_code(@topic.location_country)
    add_breadcrumb "#{country_name}", "/forum/country/#{@topic.location_country}"
    add_breadcrumb "#{Nokogiri::HTML(@topic.title).text.truncate(50)}"
  end

  def new
    @topic = Topic.new
    add_breadcrumb "Forum", "/forum"
    add_breadcrumb "New"
  end

  def edit
    add_breadcrumb "Forum", "/forum"
    country_name = AppUtils.country_name_by_country_code(@topic.location_country)
    add_breadcrumb "#{country_name}", "/forum/country/#{@topic.location_country}"
    add_breadcrumb "#{Nokogiri::HTML(@topic.title).text.truncate(50)}", "/forum/topics/#{@topic.id}"
    add_breadcrumb "Edit"
  end

  def create

    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to "/forum/topics", notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: "/forum/topics" }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to "/forum/topics/#{@topic.id}", notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: "/forum/topics/#{@topic.id}" }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :content, :safe, :closed, :trusted, :customer_id, :location_name, :location_country, :location_state, :location_city, :additional_topic)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/additional_index.html.erb
<section class="blog-page user_profile">
  <div class="container">
    <div class="row py-3">
      <div class="col-md-12 your-destinations">
        <div class="your-destionations__top">
          <% if customer_signed_in? %>
              <%= link_to '<i class="fa fa-plus"></i> New Topic'.html_safe, new_topic_path, :class=>"btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="topic-container">
          <table class="country-table table table-bordered">
            <thead>
            <tr>
              <th class="with60_p">Threads</th>
              <th class="with20_p">Last Post</th>
              <th>Posts</th>
              <th>views</th>
              <% if admin_signed_in? %>
                  <th>Action</th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% @topics.each do |topic| %>
                <tr>
                  <td>
                    <div><strong><%= link_to "#{topic.title}", "/forum/#{params["id"]}/topics/#{topic.id}" %></strong></div>
                    <div class="help-block">
                      <div>By: <%= topic.customer.profile.present? ? topic.customer.profile.name : topic.customer.name %></div>
                      <div>Created at: <%= topic.created_at.to_date.strftime("%d/%m/%Y") %></div>
                    </div>
                  </td>
                  <td>
                    <% last_post = topic.post_topics.present? ? topic.post_topics.last : topic %>
                    <div>
                      <div><strong><%= link_to "#{Nokogiri::HTML(last_post.title).text.truncate(50)}", "javascript:void(0)" %></strong></div>
                      <div class="help-block">
                        <div>By: <%= topic.customer.profile.present? ? topic.customer.profile.name : topic.customer.name %></div>
                        <div>Updated at: <%= topic.post_topics.present? ? topic.post_topics.last.updated_at.to_date.strftime("%d/%m/%Y") : topic.updated_at.to_date.strftime("%d/%m/%Y") %></div>
                      </div>
                    </div>
                  </td>
                  <td class="text-center">
                    <div>
                      <%= 1 + (topic.post_topics.present? ? topic.post_topics.size : 0 ) %>
                    </div>
                  </td>
                  <td class="pos-rel text-center">
                    <div>
                      <%= topic.view_count %>
                    </div>
                  </td>
                  <% if admin_signed_in? %>
                      <td>
                        <div class="dropdown dest_drop">
                          <a id="dLabel" href="javascript:void(0)" class="btn btn-primary btn-dest" data-toggle="dropdown" role="button" aria-haspopup="true">
                            action
                          </a>

                          <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li><%= link_to '<i class="fa fa-pencil"></i>&nbsp;&nbsp;edit'.html_safe, edit_topic_path(topic) %></li>
                            <li><%= link_to '<i class="fa fa-remove"></i>&nbsp;&nbsp;Delete'.html_safe, topic, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                          </ul>
                        </div>
                      </td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>
          </table>
          <%= will_paginate @topics, renderer: BootstrapPagination::Rails  if @topics.any? %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/topics/additional_show.html.erb
<section>
  <div class="container-fluid">
    <div class="breadcrumb">
      <%= render_breadcrumbs :tag => :li, :separator=>"" %>
    </div>
  </div>
</section>
<section class="container-fluid single-forum">
  <div class="row">
    <div class="col-md-12">
      <table class="country-table table table-bordered">
        <thead>
        <tr>
          <th class="author_col"><%= @topic.created_at.to_date.strftime("%d/%m/%Y") %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            <div>
              <div class="forum-profile">
                <% if @topic.customer.profile.present? %>
                    <% if @topic.customer.profile.avatar.present? %>
                        <div class="avatar">
                          <div class="avtr" data-avatar="<%= @topic.customer.profile.avatar %>">
                            <img src="<%= @topic.customer.profile.avatar.profile_picture %>" alt="<%= @topic.customer.profile.name %>">
                          </div>
                        </div>
                        <!-- <span>Profile Avatar</span> -->
                    <% else %>
                        <div class="avatar text-center">
                          <div class="avtr" data-avatar="<%= @topic.customer.profile.avatar %>">
                            <%= image_tag("noavatar.png") %>
                          </div>
                        </div>
                    <% end %>
                <% end %>
                <div class="porfile-area">
                  <strong class="bold"><%= @topic.customer.profile.name %> </strong>
                  <div>joined date: <%=  @topic.customer.created_at.to_date.strftime("%d/%m/%Y") %></div>
                  <div>last login: <%=  @topic.customer.last_sign_in_at.to_date.strftime("%d/%m/%Y") %></div>
                </div>
              </div>
            </div>
          </td>
          <td>
            <h1 class="forum-title"><%= @topic.title %></h1>
            <%= raw @topic.content %>
            <div class="forum-footer">
              <div class="pull-right">
                <% if customer_signed_in? %>
                    <% if current_customer.id == @topic.customer.id %>
                        <a class="btn btn-primary btn-dest" href="<%= edit_topic_path(@topic) %>"><i class="fa fa-pencil"></i>&nbsp;&nbsp;edit</a>
                    <% end %>
                    <a class="btn btn-primary btn-dest" href="<%= new_topic_post_topic_path(@topic.id) %>" data-remote="true"><i class="fa fa-reply"></i>&nbsp;&nbsp;Reply</a>
                    <a class="btn btn-primary btn-dest" href="<%= new_topic_post_topic_path(@topic.id) %>?is_quote=true&is_topic=true&topic=<%= @topic.id %>" data-remote="true"><i class="fa fa-clipboard"></i>&nbsp;&nbsp;Quote</a>
                <% else %>0
                    Login to post <a href="<%= new_customer_session_path %>" class="btn btn-primary btn-dest"><i class="fa fa-key"></i>&nbsp;&nbsp;Login</a>
                <% end %>
              </div>
              <div class="clearfix"></div>
            </div>
          </td>
        </tr>
        </tbody>
      </table>
      <% if @post_topics.present? %>
          <% @post_topics.each_with_index do |post_topic, index| %>
              <table class="country-table table table-bordered">
                <thead>
                <tr>
                  <th class="author_col"><%= @topic.created_at.to_date.strftime("%d/%m/%Y") %></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>
                    <div>
                      <div class="forum-profile">
                        <% if post_topic.customer.profile.present? %>
                            <% if post_topic.customer.profile.avatar.present? %>
                                <div class="avatar">
                                  <div class="avtr" data-avatar="<%= post_topic.customer.profile.avatar %>">
                                    <img src="<%= post_topic.customer.profile.avatar.profile_picture %>" alt="<%= post_topic.customer.profile.name %>">
                                  </div>
                                </div>
                                <!-- <span>Profile Avatar</span> -->
                            <% else %>
                                <div class="avatar text-center">
                                  <div class="avtr" data-avatar="<%= post_topic.customer.profile.avatar %>">
                                    <%= image_tag("noavatar.png") %>
                                  </div>
                                </div>
                            <% end %>
                        <% end %>
                        <div class="porfile-area">
                          <strong class="bold"><%= post_topic.customer.profile.name %></strong>
                          <div>joined date: <%=  post_topic.customer.created_at.to_date.strftime("%d/%m/%Y") %></div>
                          <div>last login: <%=  post_topic.customer.last_sign_in_at.to_date.strftime("%d/%m/%Y") %></div>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td>
                    <h1 class="forum-title"><%= post_topic.title %></h1>
                    <%= raw post_topic.content %>
                    <div class="forum-footer">
                      <div class="pull-right">
                        <% if customer_signed_in? %>
                            <% if current_customer.id == post_topic.customer.id %>
                                <a class="btn btn-primary btn-dest" href="<%= edit_topic_post_topic_path(post_topic.topic_id, post_topic.id) %>" data-remote="true"><i class="fa fa-pencil"></i>&nbsp;&nbsp;edit</a>
                            <% end %>
                            <a class="btn btn-primary btn-dest" href="<%= new_topic_post_topic_path(post_topic.topic_id) %>" data-remote="true"><i class="fa fa-reply"></i>&nbsp;&nbsp;Reply</a>
                            <a class="btn btn-primary btn-dest" href="<%= new_topic_post_topic_path(post_topic.topic_id) %>?is_quote=true&is_topic=false&topic=<%= post_topic.id %>" data-remote="true"><i class="fa fa-clipboard"></i>&nbsp;&nbsp;Quote</a>
                        <% else %>
                            Login to post <a href="<%= new_customer_session_path %>" class="btn btn-primary btn-dest"><i class="fa fa-key"></i>&nbsp;&nbsp;Login</a>
                        <% end %>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                  </td>
                </tr>
                </tbody>
              </table>
          <% end %>
      <% end %>
      <%#= will_paginate @post_topics, renderer: BootstrapPagination::Rails  if @post_topics.any? %>
    </div>
  </div>
</section>


<div id="reply-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div id="reply-content">

        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<section class="blog-page user_profile">
  <div class="container">
    <div class="row py-3">
      <div class="col-md-4 your-destinations">
        <div class="your-destionations__top">
          <% if customer_signed_in? %>
            <%= link_to '<i class="fa fa-plus"></i> New Topic'.html_safe, new_topic_path, :class=>"btn btn-primary" %>
          <% end %>
          <div class="your-destinations__bar">
            <div class="order">
              <% sortby_val = params["sortby"].present? ? params["sortby"] : ""%>
              <%#= select :sort_by, "", AppConstants::SORTING_ARRAY_FOR_TOPIC, {class: "orderby awe-select", :selected=> sortby_val} %>
              <%#= select :sort_by_type, "", AppUtils.country_list, {class: "orderby awe-select", :selected=> "", :prompt=> "Select"} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="blog-page__content rs">
          <div id="accordion" >
            <% unless @is_addition %>
              <%
                # region_hash = Topic.get_view_region(@topics_by_country)
                region = AppConstants::REGIONS_HASH[params[:region].to_i]
              %>
              <table class="country-table table table-bordered">
                <thead>
                  <tr>
                    <th>Country</th>
                    <th>Post</th>
                    <th>views</th>
                  </tr>
                </thead>
                <tbody>
                  <%
                    countries =  AppUtils.countries_from_region_by_country_code_name("#{region}")
                    countries.each do |country|
                  %>
                    <tr>
                      <td>
                        <a href="/forum/country/<%= country[1] %>"><%= country[0] %></a>
                      </td>
                      <td class="text-center">
                        <%= @topics_by_country[country[1]].size %>
                      </td>
                      <td class="text-center">
                        <%= @topics_by_country[country[1]].size != 0 ? Topic.get_view_count(@topics_by_country[country[1]]) : 0 %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
                <table class="country-table table table-bordered">
                  <thead>
                  <tr>
                    <th>Topic</th>
                    <th>Post</th>
                    <th>views</th>
                  </tr>
                  </thead>
                  <tbody>
                  <%
                    @topics.each do |topic|
                  %>
                      <tr>
                        <td>
                          <a href="/forum/<%= params["region"].to_i %>/additional/<%= topic.id %>"><%= topic.title %></a>
                        </td>
                        <td class="text-center">
                          <%= topic.post_topics.size %>
                        </td>
                        <td class="text-center">
                          <%= topic.view_count %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>