config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options :host => "https://blubeez.com"
  else
    default_url_options :host => "http://localhost:3000"
  end

  match "es" => "home#locale_index", :via => [:get], :defaults => {:locale => 'es'}
  match "en" => "home#locale_index", :via => [:get], :defaults => {:locale => 'en'}

  devise_for :admins, :skip => [:registrations], :controllers=> {sessions: "admins/sessions"}
  devise_for :customers, controllers: { 
    registrations: 'customers/registrations', 
    sessions: "customers/sessions" , 
    omniauth_callbacks: 'omniauth_callbacks',
    passwords: "customers/passwords",
    confirmations: "customers/confirmations" 
  }, path_names: { sign_in: 'signin', sign_up: 'signup'}
  get '/s/create', to: 'short_links#create'
  get '/s/:slug', to: 'short_links#show', as: :short

  resources :images, :only => [:index, :create]
  delete "/images" => "images#destroy"
  get "/multiple_image" => "images#multiple_index"
  post "/multiple_image" => "images#create_multiple"
  post "/images/update_description" => "images#update_description"

  get "/settings" => "banners#index" 
  post "/settings" => "settings#update_settings"

  resources :admin, :only=> [:show] do
    resources :banners
    get "manage-users" => "admins#manage_users"
    post "manage-users" => "admins#update_users"
  end
  get "new-admin" => "admins#new_admin"
  post "create-admin" => "admins#create_admin"
  get "manage-admin" => "admins#manage_admin"
  get "edit-admin" => "admins#edit_admin"
  post "manage-admin/:id" => "admins#update_admin"
  resources :reviews
  get "/vote/:id" => "reviews#vote"
  match '/customers/:id/finish_signup' => 'customers#finish_signup', via: [:get, :patch], :as => :finish_signup

  scope "(:locale)", :locale => /en|es/ do

    get "/destinations" => "destinations#index"
    post "/destinations"  => "destinations#create"
    get "/destinations/new" => "destinations#new"
    get "/destinations/:id/edit"  => "destinations#edit"
    get "/destinations/:id/traveller_images" => "destinations#traveller_images"
    get "/destinations/:slug" => "destinations#show"
    patch "/destinations/:id" => "destinations#update"
    put "/destinations/:id" => "destinations#update"
    delete "/destinations/:id" => "destinations#destroy"
    get "/destinations-by-country" => "destinations#country_wise_destinations"

    get "/destinations/:slug/hotels" => "hotels#index"
    post  "/destinations/:destination_id/:destination_name/hotels" => "hotels#create"
    get "/destinations/:destination_id/:destination_name/hotels/new" => "hotels#new"
    get "/destinations/:destination_id/:destination_name/hotels/:id/edit"  => "hotels#edit"
    get "/destinations/:destination_id/:destination_name/hotels/:id/:name" => "hotels#show"
    put "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"
    delete  "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#destroy"
    patch "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"

    get "/destinations/:slug/flights" => "flights#index"
    post  "/destinations/:destination_id/:destination_name/flights" => "flights#create"
    get "/destinations/:destination_id/:destination_name/flights/new" => "flights#new"
    get "/destinations/:destination_id/:destination_name/flights/:id/edit"  => "flights#edit"
    get "/destinations/:destination_id/:destination_name/flights/:id/:name" => "flights#show"
    put "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"
    delete  "/destinations/:destination_id/:destination_name/flights/:id" => "flights#destroy"
    patch "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"

    get "/attractions/:slug" => "attractions#index"
    get "/attractions/:destination_slug/:attraction_slug" => "attractions#show"
    post  "/destinations/:destination_id/:destination_name/attractions" => "attractions#create"
    get "/destinations/:destination_id/:destination_name/attractions/new" => "attractions#new"
    get "/destinations/:destination_id/:destination_name/attractions/:id/edit"  => "attractions#edit"
    get "/destinations/:destination_id/:destination_name/attractions/:id/:name" => "attractions#show"
    put "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"
    delete  "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#destroy"
    patch "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"

    get "/events/:slug" => "events#index"
    get "/events/:destination_slug/:event_slug" => "events#show"
    post  "/destinations/:destination_id/:destination_name/events" => "events#create"
    get "/destinations/:destination_id/:destination_name/events/new" => "events#new"
    get "/destinations/:destination_id/:destination_name/events/:id/edit"  => "events#edit"
    get "/destinations/:destination_id/:destination_name/events/:id/:name" => "events#show"
    put "/destinations/:destination_id/:destination_name/events/:id" => "events#update"
    delete  "/destinations/:destination_id/:destination_name/events/:id" => "events#destroy"
    patch "/destinations/:destination_id/:destination_name/events/:id" => "events#update"

    get "/all-users" => "customers#all_users"
    get "/meet-travelers" => "customers#meet_travellers"
    post 'travelers/search' => "customers#search_traveler"
    post '/validate_username' => "customers#validate_username"
    
    get "/traveler/:username" => "customers#traveler"
    get "/traveler/:username/travel_blogs" => "travel_blogs#index"
    get "back_to_blog_comment/:id" => "blog_comments#back_to_comment"
    get "reply_to_comment/:id" => "blog_comments#reply_to_comment"
    root 'home#index'
    get "/get_cities" => "destinations#cities_per_country"
    get "/get_states" => "destinations#states_per_country"
    get "/hotels" => "hotels#all_index"
    get "/flights" => "flights#all_index"
    get "/events" => "events#all_index"
    get "/attractions" => "attractions#all_index"
    get "/search" => "home#search"
    get "/blog_categories" => "travel_blogs#get_categorized_data"
    get "/blog" => "travel_blogs#all_index"
    get "/blog_main" => "travel_blogs#blog_main"
    get "/blog/post/:id" => "travel_blogs#single_post"
    get "/blog/new" => "travel_blogs#new_post"
    post "/blog/new" => "travel_blogs#create_post"
    get "/blog/edit/:id" => "travel_blogs#edit_post"
    delete "/blog/delete/:id" => "travel_blogs#destroy"
    post "/blog/edit/:id" => "travel_blogs#update_post"
    post "blog/post/:id/comment" => "blog_comments#create"
    get "dynamic_js_content.:ext" => "home#dynamic_content"
    get "/filter-destinations" => "destinations#filter_destinations"
    get "contact" => "home#contact"
    get "faq" => "home#faq"
    get "contribute" => "home#contribute"
    get "advertise" => "home#advertise"
    get "privacy" => "home#privacy"
    get "careers" => "home#careers"
    get "terms" => "home#terms"
    get "partner_with_us" => "home#partner_with_us"
    post "contact" => "home#contact_form"
    get "/about" => "home#about"
    get "/add-listing" => "home#add_listing"
    post "/add-listing" => "home#save_listing"
    get "/report-spam" => "home#report_spam"
    post "/report-spam" => "home#save_spam"
    get "/report-fraud" => "home#report_fraud"
    post "/report-fraud" => "home#save_fraud"
    post "about" => "home#about"
    post "/share-as-email" => "home#share_as_email"
    get 'wishlists/add' => "wishlists#create"
    get '/customers/:customer_id/wishlists' => "wishlists#index"
    get 'recommendations/add' => "recommendations#create"
    get '/customers/:customer_id/recommendations' => "recommendations#index"
    get '/customers/:customer_id/posts' => "customers#posts"
    post '/posts/:id/comment' => "customers#comment"
    get '/posts/:id/show' => "customers#show_post"
    get '/posts/:id/edit' => "customers#edit_post"
    post '/posts/:id/update' => "customers#update_post"
    get '/posts/:id/like' => "customers#like"
    get '/posts/:id/remove' => "customers#remove_post"
    get '/customers/:customer_id/gallery' => "customers#gallery"
    get '/customers/:customer_id/gallery/:country' => "customers#gallery_by_country"
    get '/customers/:customer_id/followings' => "customers#followings"
    get '/customers/:customer_id/followers' => "customers#followers"
    get "customers/accept_as_public_traveller" => "customers#update_visibility"
    get "/customers/create-post" => "customers#create_post"
    post "/customers/create-post" => "customers#save_post"
    get "/recommendation" => "customers#recommendation"
    get '/wishlists/auth' => "wishlists#index"
    get '/checkins/auth' => "checkins#index"
    get '/recommendation/auth' => "recommendations#index"
    delete 'customers/:customer_id/wishlists/:id' => "wishlists#destroy"
    delete 'customers/:customer_id/recommendations/:id' => "recommendations#destroy"
    get 'checkins/add' => "checkins#create"
    get 'customers/:customer_id/checkins' => "checkins#index"
    delete 'customers/:customer_id/checkins/:id' => "checkins#destroy"
    get '/terms' => "admins#terms"
    get '/faq' => "admins#faq"
    get '/careers' => "admins#careers"
    get '/privacy' => "admins#privacy"
    get '/about' => "admins#about_us"
    get '/terms/edit' => "admins#edit_terms"
    get '/faq/edit' => "admins#edit_faq"
    get '/careers/edit' => "admins#edit_careers"
    get '/privacy/edit' => "admins#edit_privacy"
    get '/about/edit' => "admins#edit_about_us"
    post '/terms/edit' => "admins#update_terms"
    post '/faq/edit' => "admins#update_faq"
    post '/careers/edit' => "admins#update_careers"
    post '/privacy/edit' => "admins#update_privacy"
    post '/about/edit' => "admins#update_about_us"
    get "/change-status" => "customers#change_status"
    post "/change-status" => "customers#update_status"

app/models/banner.rb
class Banner < ActiveRecord::Base
  belongs_to :admin
  mount_uploader :banner_image, ImageUploader
  has_one :temp_image, dependent: :destroy
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_banner, only: [:show, :edit, :update, :destroy]
  layout "v2_admin"

  # GET /banners
  # GET /banners.json
  def index
    @admin = current_admin
    @banners = @admin.banners.all
  end

  # GET /banners/new
  def new
    @admin = Admin.find(params["admin_id"])
    @banner = @admin.banners.new
  end

  # GET /banners/1/edit
  def edit
    @admin = Admin.find(params["admin_id"])
    @banner = @admin.banners.find(params["id"])
  end

  # POST /banners
  # POST /banners.json
  def create
    @admin = Admin.find(params["admin_id"])
    @banner = @admin.banners.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to admin_banners_path, notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    @admin = Admin.find(params["admin_id"])
    @banner = @admin.banners.find(params[:id])

    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to admin_banners_path, notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to admin_banners_path, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:banner_image, :admin_id, :title, :desc, :button_text, :button_link)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_edit.html.erb
<%= render 'form' %>
<%#= link_to '<< Back', admin_banners_path, :class=>"btn btn-primary", remote: true %>

app/views/banners/_form.html.erb
<% url_path = params[:action] == "new" ? admin_banners_path : admin_banner_path %>
<%= form_for(@banner, :url=> url_path, :html => {:multipart => true}) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-item">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :desc, "Description" %>
        <%= f.text_area :desc, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :button_text %>
        <%= f.text_field :button_text, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :button_link %>
        <%= f.text_field :button_link, class: "form-control" %>
      </div>
      <div class="form-item">
        <%= f.label :banner_image %>
        <%= f.file_field :banner_image, class: "form-control" %>
      </div>
      <%= f.hidden_field :admin_id %>
      <div class="form-actions">
        <%= f.submit 'Update', :class=>"btn btn-primary" %>
        <%= link_to '<< Back', admin_banners_path, :class=>"btn btn-primary", remote: true %>
      </div>

    </div>
  </div>
<% end %>

app/views/banners/_index.html.erb
<div class="banner-wrap row clearfix">
  <% @banners.each do |banner| %>
    <div class="banner-item col-md-4">
      <img src="<%= banner.banner_image %>">
      <div class="banner-links">
        <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_admin_banner_path(banner.admin_id, banner.id), :class=>"btn-primary" %>
        <%= link_to '<i class="fa fa-trash"></i>'.html_safe, admin_banner_path(banner.admin_id, banner.id), :class=>"btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>    
  <% end %>
</div>
<div class="clearfix"></div>
<div class="">
  <%= link_to '<i class="fa fa-plus"></i> &nbsp;&nbsp;New Banner'.html_safe, new_admin_banner_path(@admin.id), remote: true, class: "btn btn-primary btn-sm" %>
</div>

app/views/banners/_new.html.erb
<%= render 'form' %>

<%#= link_to '<< Back', admin_banners_path(@admin.id), remote: true %>

app/views/banners/edit.html.erb
<!-- <section class="awe-parallax page-heading-demo">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="blog-heading-content text-uppercase"><h2>Banner</h2></div>
  </div>
</section> -->

<section class="blog-page user_profile">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-4">
        <%= render :partial=> "admins/left_menu" %>
      </div>
      <div class="col-md-8 col-sm-8">
        <div class="blog-page__content rs">
          <div id="main-content" class="right_content">
            <%= render :partial=> "edit" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/banners/edit.js.erb
$("#main-content").html("<%= escape_javascript(render(:partial=> 'edit')) %>");

app/views/banners/index.html.erb
<!-- <section class="awe-parallax page-heading-demo">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="blog-heading-content text-uppercase"><h2>Banner</h2></div>
  </div>
</section> -->

<section class="blog-page user_profile">
  <div class="blog-page__content rs">
    <div id="main-content" class="right_content">
      <%= render :partial=> "index" %>
    </div>
  </div>
</section>

app/views/banners/index.js.erb
$("#main-content").html("<%= escape_javascript(render(:partial=> 'index')) %>");

app/views/banners/new.html.erb
<section class="awe-parallax page-heading-demo">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="blog-heading-content text-uppercase"><h2>Banner</h2></div>
  </div>
</section>

<section class="blog-page user_profile">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= render :partial=> "admins/left_menu" %>
      </div>
      <div class="col-md-8">
        <div class="blog-page__content rs">
          <div id="main-content" class="right_content">
			<%= render :partial=> "new" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/banners/new.js.erb
$("#main-content").html("<%= escape_javascript(render(:partial=> 'new')) %>");

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Banner images:</strong>
  <%= @banner.banner_images %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @banner.admin %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>