config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options :host => "https://blubeez.com"
  else
    default_url_options :host => "http://localhost:3000"
  end

  match "es" => "home#locale_index", :via => [:get], :defaults => {:locale => 'es'}
  match "en" => "home#locale_index", :via => [:get], :defaults => {:locale => 'en'}

  devise_for :admins, :skip => [:registrations], :controllers=> {sessions: "admins/sessions"}
  devise_for :customers, controllers: { 
    registrations: 'customers/registrations', 
    sessions: "customers/sessions" , 
    omniauth_callbacks: 'omniauth_callbacks',
    passwords: "customers/passwords",
    confirmations: "customers/confirmations" 
  }, path_names: { sign_in: 'signin', sign_up: 'signup'}
  get '/s/create', to: 'short_links#create'
  get '/s/:slug', to: 'short_links#show', as: :short

  resources :images, :only => [:index, :create]
  delete "/images" => "images#destroy"
  get "/multiple_image" => "images#multiple_index"
  post "/multiple_image" => "images#create_multiple"
  post "/images/update_description" => "images#update_description"

  get "/settings" => "banners#index" 
  post "/settings" => "settings#update_settings"

  resources :admin, :only=> [:show] do
    resources :banners
    get "manage-users" => "admins#manage_users"
    post "manage-users" => "admins#update_users"
  end
  get "new-admin" => "admins#new_admin"
  post "create-admin" => "admins#create_admin"
  get "manage-admin" => "admins#manage_admin"
  get "edit-admin" => "admins#edit_admin"
  post "manage-admin/:id" => "admins#update_admin"
  resources :reviews
  get "/vote/:id" => "reviews#vote"
  match '/customers/:id/finish_signup' => 'customers#finish_signup', via: [:get, :patch], :as => :finish_signup

  scope "(:locale)", :locale => /en|es/ do

    get "/destinations" => "destinations#index"
    post "/destinations"  => "destinations#create"
    get "/destinations/new" => "destinations#new"
    get "/destinations/:id/edit"  => "destinations#edit"
    get "/destinations/:id/traveller_images" => "destinations#traveller_images"
    get "/destinations/:slug" => "destinations#show"
    patch "/destinations/:id" => "destinations#update"
    put "/destinations/:id" => "destinations#update"
    delete "/destinations/:id" => "destinations#destroy"
    get "/destinations-by-country" => "destinations#country_wise_destinations"

    get "/destinations/:slug/hotels" => "hotels#index"
    post  "/destinations/:destination_id/:destination_name/hotels" => "hotels#create"
    get "/destinations/:destination_id/:destination_name/hotels/new" => "hotels#new"
    get "/destinations/:destination_id/:destination_name/hotels/:id/edit"  => "hotels#edit"
    get "/destinations/:destination_id/:destination_name/hotels/:id/:name" => "hotels#show"
    put "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"
    delete  "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#destroy"
    patch "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"

    get "/destinations/:slug/flights" => "flights#index"
    post  "/destinations/:destination_id/:destination_name/flights" => "flights#create"
    get "/destinations/:destination_id/:destination_name/flights/new" => "flights#new"
    get "/destinations/:destination_id/:destination_name/flights/:id/edit"  => "flights#edit"
    get "/destinations/:destination_id/:destination_name/flights/:id/:name" => "flights#show"
    put "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"
    delete  "/destinations/:destination_id/:destination_name/flights/:id" => "flights#destroy"
    patch "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"

    get "/attractions/:slug" => "attractions#index"
    get "/attractions/:destination_slug/:attraction_slug" => "attractions#show"
    post  "/destinations/:destination_id/:destination_name/attractions" => "attractions#create"
    get "/destinations/:destination_id/:destination_name/attractions/new" => "attractions#new"
    get "/destinations/:destination_id/:destination_name/attractions/:id/edit"  => "attractions#edit"
    get "/destinations/:destination_id/:destination_name/attractions/:id/:name" => "attractions#show"
    put "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"
    delete  "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#destroy"
    patch "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"

    get "/events/:slug" => "events#index"
    get "/events/:destination_slug/:event_slug" => "events#show"
    post  "/destinations/:destination_id/:destination_name/events" => "events#create"
    get "/destinations/:destination_id/:destination_name/events/new" => "events#new"
    get "/destinations/:destination_id/:destination_name/events/:id/edit"  => "events#edit"
    get "/destinations/:destination_id/:destination_name/events/:id/:name" => "events#show"
    put "/destinations/:destination_id/:destination_name/events/:id" => "events#update"
    delete  "/destinations/:destination_id/:destination_name/events/:id" => "events#destroy"
    patch "/destinations/:destination_id/:destination_name/events/:id" => "events#update"

    get "/all-users" => "customers#all_users"
    get "/meet-travelers" => "customers#meet_travellers"
    post 'travelers/search' => "customers#search_traveler"
    post '/validate_username' => "customers#validate_username"
    
    get "/traveler/:username" => "customers#traveler"
    get "/traveler/:username/travel_blogs" => "travel_blogs#index"
    get "back_to_blog_comment/:id" => "blog_comments#back_to_comment"
    get "reply_to_comment/:id" => "blog_comments#reply_to_comment"
    root 'home#index'
    get "/get_cities" => "destinations#cities_per_country"
    get "/get_states" => "destinations#states_per_country"
    get "/hotels" => "hotels#all_index"
    get "/flights" => "flights#all_index"
    get "/events" => "events#all_index"
    get "/attractions" => "attractions#all_index"
    get "/search" => "home#search"
    get "/blog_categories" => "travel_blogs#get_categorized_data"
    get "/blog" => "travel_blogs#all_index"
    get "/blog_main" => "travel_blogs#blog_main"
    get "/blog/post/:id" => "travel_blogs#single_post"
    get "/blog/new" => "travel_blogs#new_post"
    post "/blog/new" => "travel_blogs#create_post"
    get "/blog/edit/:id" => "travel_blogs#edit_post"
    delete "/blog/delete/:id" => "travel_blogs#destroy"
    post "/blog/edit/:id" => "travel_blogs#update_post"
    post "blog/post/:id/comment" => "blog_comments#create"
    get "dynamic_js_content.:ext" => "home#dynamic_content"
    get "/filter-destinations" => "destinations#filter_destinations"
    get "contact" => "home#contact"
    get "faq" => "home#faq"
    get "contribute" => "home#contribute"
    get "advertise" => "home#advertise"
    get "privacy" => "home#privacy"
    get "careers" => "home#careers"
    get "terms" => "home#terms"
    get "partner_with_us" => "home#partner_with_us"
    post "contact" => "home#contact_form"
    get "/about" => "home#about"
    get "/add-listing" => "home#add_listing"
    post "/add-listing" => "home#save_listing"
    get "/report-spam" => "home#report_spam"
    post "/report-spam" => "home#save_spam"
    get "/report-fraud" => "home#report_fraud"
    post "/report-fraud" => "home#save_fraud"
    post "about" => "home#about"
    post "/share-as-email" => "home#share_as_email"
    get 'wishlists/add' => "wishlists#create"
    get '/customers/:customer_id/wishlists' => "wishlists#index"
    get 'recommendations/add' => "recommendations#create"
    get '/customers/:customer_id/recommendations' => "recommendations#index"
    get '/customers/:customer_id/posts' => "customers#posts"
    post '/posts/:id/comment' => "customers#comment"
    get '/posts/:id/show' => "customers#show_post"
    get '/posts/:id/edit' => "customers#edit_post"
    post '/posts/:id/update' => "customers#update_post"
    get '/posts/:id/like' => "customers#like"
    get '/posts/:id/remove' => "customers#remove_post"
    get '/customers/:customer_id/gallery' => "customers#gallery"
    get '/customers/:customer_id/gallery/:country' => "customers#gallery_by_country"
    get '/customers/:customer_id/followings' => "customers#followings"
    get '/customers/:customer_id/followers' => "customers#followers"
    get "customers/accept_as_public_traveller" => "customers#update_visibility"
    get "/customers/create-post" => "customers#create_post"
    post "/customers/create-post" => "customers#save_post"
    get "/recommendation" => "customers#recommendation"
    get '/wishlists/auth' => "wishlists#index"
    get '/checkins/auth' => "checkins#index"
    get '/recommendation/auth' => "recommendations#index"
    delete 'customers/:customer_id/wishlists/:id' => "wishlists#destroy"
    delete 'customers/:customer_id/recommendations/:id' => "recommendations#destroy"
    get 'checkins/add' => "checkins#create"
    get 'customers/:customer_id/checkins' => "checkins#index"
    delete 'customers/:customer_id/checkins/:id' => "checkins#destroy"
    get '/terms' => "admins#terms"
    get '/faq' => "admins#faq"
    get '/careers' => "admins#careers"
    get '/privacy' => "admins#privacy"
    get '/about' => "admins#about_us"
    get '/terms/edit' => "admins#edit_terms"
    get '/faq/edit' => "admins#edit_faq"
    get '/careers/edit' => "admins#edit_careers"
    get '/privacy/edit' => "admins#edit_privacy"
    get '/about/edit' => "admins#edit_about_us"
    post '/terms/edit' => "admins#update_terms"
    post '/faq/edit' => "admins#update_faq"
    post '/careers/edit' => "admins#update_careers"
    post '/privacy/edit' => "admins#update_privacy"
    post '/about/edit' => "admins#update_about_us"
    get "/change-status" => "customers#change_status"
    post "/change-status" => "customers#update_status"

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def locale_index
		if request.env["HTTP_REFERER"].present? && (request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]) && params["locale"].present?
			redirect_to request.env["HTTP_REFERER"]
		else
			redirect_to root_path
		end
	end

	def index
		@destinations = Destination.includes(:attractions, :ratings, :events, :images).with_main_image.last(9)
		@banners = Banner.all
		@blogs = TravelBlog.includes(:blog_comments, :customer).last(5)
		@hot_trips = @destinations.first(5)
		@popular_packages = @destinations.last(5)
		@customers = Customer.includes(:profile).where("is_public = ?", AppConstants::YES)
		@countries_wise_place_hash = AppUtils.get_popular_countries
		render layout: "v2"
	end

	def search
		unless params["name"].present?
			flash.now[:error] = "Please select any data"
		end	
	end

	def contact_form
		ContactJob.perform_async(params["contact"])
    flash.now[:notice] = "Succeeded"
		redirect_to "/contact"
	end

	def contact
		
	end

	def share_as_email
		if EmailValidator.valid?(params["share"]["email"])
			AirvtrMailer.blog_share_email(params["share"]["email"], params["url_path"].first).deliver_now!
		else
			flash[:error] = "Failed"
		end
	end

	def about
		render layout: "v2"
	end
	
	def partner_with_us
		render layout: "v2"
	end
  def add_listing
		render layout: "v2"
	end

  def save_listing
		listing = Listing.new(listing_params)
		if listing.save
			flash[:notice] = "Thank you for registering with us, We will review the above details and get in touch with you soon."
		else
			flash[:error] = listing.errors.full_messages.join("<br/>")
		end
		redirect_to "/add-listing"
	end

  def report_spam
		render layout: "v2"
	end

  def save_spam
		report_spam = ReportSpam.new(report_spam_params)
		if report_spam.save
			ReportSpamJob.perform_async(report_spam_params)
			flash[:notice] = "Sorry for the inconvenience, We will review the above details and get in touch with you soon."
		else
			flash[:error] = report_spam.errors.full_messages.join("<br/>")
		end
		redirect_to "/report-spam"
	end

	def report_fraud
		render layout: "v2"
	end

	 def save_fraud
		report_fraud = ReportFraud.new(report_fraud_params)
		if report_fraud.save
			ReportFraudJob.perform_async(report_fraud_params)
			flash[:notice] = "Sorry for the inconvenience, We will review the above details and get in touch with you soon."
		else
			flash[:error] = report_fraud.errors.full_messages.join("<br/>")
		end
		redirect_to "/report-fraud"
	end

  private
  def listing_params
		params.require(:listing).permit(:name, :phone, :email, :is_read, :location, :service_desc, :website, :is_owner, :message)
	end

  def report_spam_params
		params.require(:report_spam).permit(:name, :email, :is_registered_with_blubeez, :phone, :spam_against_person, :spam_profile_link, :spam_type, :message)
	end

	def report_fraud_params
		params.require(:report_fraud).permit(:name, :email, :is_registered_with_blubeez, :phone, :fraud_against_person, :fraud_against_url, :message)
	end

end

app/views/home/_dynamic_content.html.erb
var search_data = <%= raw search_data %>


$.widget( "custom.catcomplete", $.ui.autocomplete, {
	_create: function() {
	  this._super();
	  this.widget().menu( "option", "items", "> :not(.ui-autocomplete-category)" );
	},
	_renderMenu: function( ul, items ) {
	  var that = this,
	    currentCategory = "";
	  $.each( items, function( index, item ) {
	    var li;
	    if ( item.category != currentCategory ) {
	      ul.append( "<li class='ui-autocomplete-category'>" + item.category + "</li>" );
	      currentCategory = item.category;
	    }
	    li = that._renderItemData( ul, item );
	    if ( item.category ) {
	      li.attr( "aria-label", item.category + " : " + item.label );
	    }
	  });
		ul.appendTo("#search-box")
	}
});


$(function() {
	$( "#home-search" ).catcomplete({
  		delay: 0,
  		source: search_data,
  		position:{
	  		within: "#search-box"
  		},
  		select: function(event, ui) {
  			$.ajax({
				url: '/search',
				data: {name: ui.item.label, search_type: ui.item.category},
				error: function(result){
					console.log(result);
				}
			})
	    }
	});
});

app/views/home/_header.html.erb
<div id="fb-root"></div>
<% if is_prod? %>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=1683746651911114";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <script src="https://apis.google.com/js/platform.js" async defer></script>
<% end %>
<div class="bg-header">
  <% if false %>
    <header class="header-removable text-center"> 
      <div class="col-md-2 text-center"><a href="/contact"><i class="fa fa-envelope"></i> info@airvtr.com</a></div>
      <!-- <div class="col-md-6 text-center hidden-xs">Get <div class="discount-label green"> <span>30%</span> </div> discount on hotels now by registering with Airvtr! <a href="#">View More</a></div>
       -->
       <div class="col-md-6 text-center hidden-xs quote-header">
         “Lets get flying, and go everywhere with Airvtr”
       </div>
      <div class="col-md-4">
        <% if false %>
          <!-- need to add Later -->
          <span><a href="#lang" data-toggle="modal" data-target="#lang"><i class="fa fa-globe"></i>&nbsp;&nbsp;Language&nbsp;</a></span>
        <% end %>
        <% unless customer_signed_in? || admin_signed_in? %>
            <span class="login"><a href="<%= new_customer_session_path %>"><i class="fa fa-key"></i>&nbsp;&nbsp;Login</a>
            </span>
            <span class="register"><a href="<%= new_customer_registration_path %>"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Register</a></span>
        <% else %>
          <% logout_path = customer_signed_in? ? destroy_customer_session_path : destroy_admin_session_path %>
          <span class="login"><a href="<%= logout_path %>" data-method="delete"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;Log Out</a></span>
        <% end %>
      </div>
       
    </header>
  <% end %>
  <header id="header-page">
    <div class="header-page__inner">
      <div class="container">
        <div class="logo"><a href="/"><%= image_tag("bbn2.png") %></a></div>
        <nav class="navigation awe-navigation" data-responsive="1200">
          <ul class="menu-list">
            <li class="menu-item-has-children <%= params["controller"] == "home" ? "current-menu-parent" : "" %>"><a href="/">Home</a>
            </li>
            <li class="menu-item-has-children <%= params["controller"] == "destinations" ? "current-menu-parent" : "" %>"><a href="<%= destinations_path %>">Destinations</a>
            </li>
            <% if false %>
              <!-- Disabling Temprorily as Usha told to hide -->
              <li class="menu-item-has-children <%= params["controller"] == "hotels" ? "current-menu-parent" : "" %>"><a href="/hotels">Hotels</a>
               </li>
              <li class="menu-item-has-children <%= params["controller"] == "flights" ? "current-menu-parent" : "" %>"><a href="/flights">Flights</a>
              </li>
              <li class="menu-item-has-children <%= params["controller"] == "events" ? "current-menu-parent" : "" %>"><a href="/events">Events</a>
              </li>
              <li class="menu-item-has-children <%= params["controller"] == "attractions" ? "current-menu-parent" : "" %>"><a href="/attractions">Attractions</a>
              </li>
            <% end %>
            <li class="menu-item-has-children <%= params["controller"] == "customers" ? "current-menu-parent" : "" %>">
              <a href="/meet-travelers">Meet Travellers</a>
            </li>
              
            <% destin_c = params["controller"] == "forums"  || params["controller"] == "insurance" %>
              <li class="menu-item-has-children <%=  destin_c ? "current-menu-parent" : "" %>" ><a href="/forum">Forums</a>
                <!-- <ul class="sub-menu">
                  <li class="menu-item-has-children <%#= params["controller"] == "forums" ? "current-menu-parent" : "" %>"><a href="#">Forums</a>
                  </li>
                </ul>
            </li>-->
            <li class="menu-item-has-children <%= params["controller"] == "travel_blog" ? "current-menu-parent" : "" %>"><a href="/blog_main">Blogs</a>
              </li>
              <% if false %>
                  <% if customer_signed_in? %>
                    <li class="menu-item-has-children">
                      <a href="javascript:void(0)"><%= current_customer.fullname %></a>
                      <!-- <ul class="sub-menu">
                        <li><a href="/customers/<%= current_customer.id %>/profile">Profile</a></li>
                        <li><a href="/customers/<%= current_customer.id %>/travel_blogs">Travel Blog</a></li>
                        <li><a href="/customers/<%= current_customer.id %>/trips">Travel History</a></li>
                        <li><a href="<%#= customer_photos_path(current_customer.id) %>">Photos/videos</a></li>
                      </ul>  -->
                    </li>
                    <% if @notification.present? %>
                        <li class="menu-item-has-children">
                          <a href="javascript:void(0)">
                            <i class="fa fa-envelope"></i>
                          </a>
                          <ul class="sub-menu">
                            <!--
                              TODO
                              styling need to be added.
                              once read notification functionality need to be added
                            -->
                            <% @notification.each do |notify| %>
                                <% n_html, n_link = AppUtils.get_notification_format(notify) %>
                                <li>
                                  <a href="<%= n_link %>">
                                    <%= n_html.html_safe %>
                                  </a>
                                </li>
                            <% end %>
                          </ul>
                        </li>
                    <% end %>
                  <% elsif admin_signed_in? %>
                    <li class="menu-item-has-children"><a href="javascript:void(0)"><%= current_admin.email %></a>
                      <ul class="sub-menu">
                        <li><a href="/settings">Settings</a></li>
                      </ul>
                    </li>
                  <% end %>
                  <% end %>
             
          <% if customer_signed_in? %>
            <li class="nav-item <%= params["controller"] == "profile" ? "active" : "" %>">
              <a href="javascript:void(0)" class="nav-link"><%= current_customer.fullname %></a>
              <ul class="sub-menu rounded list-unstyled px-3" style="border-radius: 1.30rem !important;">
                <li class="text-center"style="background-color: white;">
                  <a href="/traveler/<%= current_customer.username %>" style="font-weight: unset;border: white;font-size: x-large;color:#f85959;" >Profile</a>
                </li>
  
                <li class="pb-2 text-center" style="background-color: white;">
                  <a href="<%= destroy_customer_session_path %>" data-method="delete" class="btn btn-primary" style="border-bottom: 2px solid;font-size: 18px;"><span >Sign Out</span></a>
                </li>
              </ul>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item ml-3">
              <a href="javascript:void(0)" class="nav-link"><%= current_admin.email %></a>
              <ul class="sub-menu rounded list-unstyled px-3" style="border-radius: 1.30rem !important;">
                <li class="text-center" >
                  <a href="/settings" style="font-size: x-large;">Settings</a>
                </li>
  
                <li class="py-3 text-center">
                  <a href="<%= destroy_admin_session_path %>" data-method="delete" class="btn btn-primary" style="border-bottom: 2px solid;font-size: 18px;"><span>Sign Out</span></a>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item cta ml-3">
              <a href="<%= new_customer_session_path %>" class="nav-link"><span style="color: white;">Sign In</span></a></li>
          
          <% end %> 
          </ul>
        </nav>
        <% if false %>
          <div id="search-box" class="search-box"><span class="searchtoggle"><i class="awe-icon awe-icon-search"></i></span>
            <form class="form-search">
              <div class="form-item"><input id="home-search" type="text" placeholder="Search your destination &amp; hit enter" value=""></div>
            </form>
          </div>
        <% end %>
        
      </div>
    </div>
  </header>
</div>

app/views/home/contribute.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="title">
                    <h2>Become a Contributor</h2>
                </div>
                <blockquote>
                    <p>
                        Are you interested in showcasing your writing or photography talent? If you have answered the question in affirmative, this is the place to be. At Airvtr, we appreciate well-written content and invite you to be a contributor. Write about your experiences; send them across. Our editors will have a look. We will publish them on the site and or post them on our social media channels.
                    </p>
                    <p>
                        To become a contributor and to build a lasting relationship, shoot us an email on <a href="mailto:contact@airvtr.com">contact@airvtr.com</a>
                    </p>
                </blockquote>
            </div>
        </div>
    </div>
</section>

app/views/home/dynamic_content.html.erb
<%= render :partial=> "dynamic_content" %>

app/views/home/index.html.erb
<div class="hero-wrap " style="background-image: url('<%= asset_path("home_bg.jpg") %>')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
      <div class="col-md-8 offset-md-2 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">

        <h1 class="" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
          Meet. Share. Explore. Discover.
        </h1>

        <p class="mb-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Redefine the world of travel</p>

        <div class="block-17 my-1">
          <form action="javascript:void(0)" method="post" class="d-block d-flex" autocomplete="off">
            <div class="fields d-block d-flex">
              <div class="textfield-search one-third">
                <img src="<%= image_path('map.png')%>" class="location-img"/>
                <input type="text" class="form-control" id="home-search" placeholder="Ex: Places, People">
              </div>
              <!-- <div class="select-wrap one-third">
                <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                <select name="" id="" class="form-control" placeholder="Keyword search">
                  <option value="">Where</option>
                  <option value="">San Francisco USA</option>
                  <option value="">Berlin Germany</option>
                  <option value="">Lodon United Kingdom</option>
                  <option value="">Paris Italy</option>
                </select>
              </div>
            </div> -->
            <input type="submit" class="search-submit btn btn-primary" value="Search">  
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section ftco-destination">
  <div class="container">
    <div class="row justify-content-start mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate">
        <h2 class="mb-4"><strong>Featured Destinations </strong></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="destination-slider-new ftco-animate d-flex flex-wrap justify-content-between">
          <% @destinations.each do |destination| %>
            <% @countryies = AppUtils.country_list_by_first_letter destination.destination_country.to_s %>

            <div class="item">
              <div class="destination">
                <a href="#" class="img d-flex justify-content-center align-items-center" style="background-image: url(<%= destination.image_url %>);">     
                </a>
                <div class="text p-4">
                  <h3 class="mb-2 d-flex">
                    <a href="/destinations/<%= destination.slug %>" class="dest-title" data-turbolinks="false">
                      <%= destination.destination_name %><br/>
                    </a>
                    <% if customer_signed_in? %>
                      <a data-remote="true" id="wish_<%= destination.id %>" href="/wishlists/add?wish[customer_id]=<%= current_customer.id %>&wish[destination_id]=<%= destination.id %>" class="wishlist ml-auto mr-1">
                        <% if destination.is_in_wishlist?(current_customer.id) %>
                          <%= image_tag "wishlist-added.png", title: "Add to wishlist" %>
                        <% else %>
                          <%= image_tag "wishlist-add.png", title: "Add to wishlist" %>
                        <% end %>
                      </a>
                      <a data-remote="true" id="checkin_<%= destination.id %>" href="/checkins/add?checkin[customer_id]=<%= current_customer.id %>&checkin[destination_id]=<%= destination.id %>" class="checkin">
                        <% if destination.is_checkedin?(current_customer.id) %>
                          <%= image_tag "checked-in.png", title: "Add to checkin" %>
                        <% else %>
                          <%= image_tag "check-in.png", title: "Add to checkin" %>
                        <% end %>
                      </a>
                    <% else %>
                      <a id="wish_<%= destination.id %>" href="/wishlists/auth" class="wishlist ml-auto mr-1">
                        <%= image_tag "wishlist-add.png", title: "Add to wishlist" %>
                      </a>
                      <a id="checkin_<%= destination.id %>" href="/checkins/auth" class="checkin">
                        <%= image_tag "check-in.png", title: "Add to checkin" %>
                      </a>
                    <% end %>
                  </h3>
                  <div>
                    <a href="/destinations-by-country?keyword=<%= destination.destination_country.first(1)%>" class="dest-title d-flex" data-turbolinks="false">
                      <h4>
                      <span class="flag-icon flag-icon-<%= destination.destination_country.downcase %>"></span>
                      </h4>
                    
                      <small class="h5 p-1 sec-color" style="color: #2599e0;">
                        <%= AppUtils.country_name_by_country_code(destination.destination_country) %>
                      </small>
                    </a>
                  </div>
                  <a href="/attractions/<%= destination.slug %>" data-turbolinks="false">
                    <span class="listing">Attractions</span><br/>
                    <%= image_tag('attraction.png') %>&nbsp;&nbsp;<%= destination.attractions.length %> 
                  </a>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="pt-5 text-center">
      <a href="/destinations" class="btn btn-primary" data-turbolinks="false">Discover More</a>
    </div>
  </div>
</section>

<% if false %>
  <section class="ftco-section pt-0">
    <div class="container">
      <div class="row justify-content-start mb-5 pb-3">
        <div class="col-md-7 heading-section ftco-animate">
          <span class="subheading">Popular</span>
          <h2 class="mb-4"><strong>Popular</strong> places to visit</h2>
        </div>
      </div>

      <div class="row">
        <% @countries_wise_place_hash.each do |country, states| %>
          <% states.each do |state, count| %>
            <div class="col-md-4 popular-destinations">
              <strong><%= state %></strong>, <%= country %> (<small><%= count %> Places</small>) 
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>