config/routes.rb
  devise_for :customers, controllers: { 
    registrations: 'customers/registrations', 
    sessions: "customers/sessions" , 
    omniauth_callbacks: 'omniauth_callbacks',
    passwords: "customers/passwords",
    confirmations: "customers/confirmations" 
  }, path_names: { sign_in: 'signin', sign_up: 'signup'}
  get '/s/create', to: 'short_links#create'
  get '/s/:slug', to: 'short_links#show', as: :short

  resources :images, :only => [:index, :create]
  delete "/images" => "images#destroy"
  get "/multiple_image" => "images#multiple_index"
  post "/multiple_image" => "images#create_multiple"
  post "/images/update_description" => "images#update_description"

  get "/settings" => "banners#index" 
  post "/settings" => "settings#update_settings"

  resources :admin, :only=> [:show] do
    resources :banners
    get "manage-users" => "admins#manage_users"
    post "manage-users" => "admins#update_users"
  end
  get "new-admin" => "admins#new_admin"
  post "create-admin" => "admins#create_admin"
  get "manage-admin" => "admins#manage_admin"
  get "edit-admin" => "admins#edit_admin"
  post "manage-admin/:id" => "admins#update_admin"
  resources :reviews
  get "/vote/:id" => "reviews#vote"
  match '/customers/:id/finish_signup' => 'customers#finish_signup', via: [:get, :patch], :as => :finish_signup

  scope "(:locale)", :locale => /en|es/ do

    get "/destinations" => "destinations#index"
    post "/destinations"  => "destinations#create"
    get "/destinations/new" => "destinations#new"
    get "/destinations/:id/edit"  => "destinations#edit"
    get "/destinations/:id/traveller_images" => "destinations#traveller_images"
    get "/destinations/:slug" => "destinations#show"
    patch "/destinations/:id" => "destinations#update"
    put "/destinations/:id" => "destinations#update"
    delete "/destinations/:id" => "destinations#destroy"
    get "/destinations-by-country" => "destinations#country_wise_destinations"

    get "/destinations/:slug/hotels" => "hotels#index"
    post  "/destinations/:destination_id/:destination_name/hotels" => "hotels#create"
    get "/destinations/:destination_id/:destination_name/hotels/new" => "hotels#new"
    get "/destinations/:destination_id/:destination_name/hotels/:id/edit"  => "hotels#edit"
    get "/destinations/:destination_id/:destination_name/hotels/:id/:name" => "hotels#show"
    put "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"
    delete  "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#destroy"
    patch "/destinations/:destination_id/:destination_name/hotels/:id" => "hotels#update"

    get "/destinations/:slug/flights" => "flights#index"
    post  "/destinations/:destination_id/:destination_name/flights" => "flights#create"
    get "/destinations/:destination_id/:destination_name/flights/new" => "flights#new"
    get "/destinations/:destination_id/:destination_name/flights/:id/edit"  => "flights#edit"
    get "/destinations/:destination_id/:destination_name/flights/:id/:name" => "flights#show"
    put "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"
    delete  "/destinations/:destination_id/:destination_name/flights/:id" => "flights#destroy"
    patch "/destinations/:destination_id/:destination_name/flights/:id" => "flights#update"

    get "/attractions/:slug" => "attractions#index"
    get "/attractions/:destination_slug/:attraction_slug" => "attractions#show"
    post  "/destinations/:destination_id/:destination_name/attractions" => "attractions#create"
    get "/destinations/:destination_id/:destination_name/attractions/new" => "attractions#new"
    get "/destinations/:destination_id/:destination_name/attractions/:id/edit"  => "attractions#edit"
    get "/destinations/:destination_id/:destination_name/attractions/:id/:name" => "attractions#show"
    put "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"
    delete  "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#destroy"
    patch "/destinations/:destination_id/:destination_name/attractions/:id" => "attractions#update"

    get "/events/:slug" => "events#index"
    get "/events/:destination_slug/:event_slug" => "events#show"
    post  "/destinations/:destination_id/:destination_name/events" => "events#create"
    get "/destinations/:destination_id/:destination_name/events/new" => "events#new"
    get "/destinations/:destination_id/:destination_name/events/:id/edit"  => "events#edit"
    get "/destinations/:destination_id/:destination_name/events/:id/:name" => "events#show"
    put "/destinations/:destination_id/:destination_name/events/:id" => "events#update"
    delete  "/destinations/:destination_id/:destination_name/events/:id" => "events#destroy"
    patch "/destinations/:destination_id/:destination_name/events/:id" => "events#update"

    get "/all-users" => "customers#all_users"
    get "/meet-travelers" => "customers#meet_travellers"
    post 'travelers/search' => "customers#search_traveler"
    post '/validate_username' => "customers#validate_username"
    
    get "/traveler/:username" => "customers#traveler"
    get "/traveler/:username/travel_blogs" => "travel_blogs#index"
    get "back_to_blog_comment/:id" => "blog_comments#back_to_comment"
    get "reply_to_comment/:id" => "blog_comments#reply_to_comment"
    root 'home#index'
    get "/get_cities" => "destinations#cities_per_country"
    get "/get_states" => "destinations#states_per_country"
    get "/hotels" => "hotels#all_index"
    get "/flights" => "flights#all_index"
    get "/events" => "events#all_index"
    get "/attractions" => "attractions#all_index"
    get "/search" => "home#search"
    get "/blog_categories" => "travel_blogs#get_categorized_data"
    get "/blog" => "travel_blogs#all_index"
    get "/blog_main" => "travel_blogs#blog_main"
    get "/blog/post/:id" => "travel_blogs#single_post"
    get "/blog/new" => "travel_blogs#new_post"
    post "/blog/new" => "travel_blogs#create_post"
    get "/blog/edit/:id" => "travel_blogs#edit_post"
    delete "/blog/delete/:id" => "travel_blogs#destroy"
    post "/blog/edit/:id" => "travel_blogs#update_post"
    post "blog/post/:id/comment" => "blog_comments#create"
    get "dynamic_js_content.:ext" => "home#dynamic_content"
    get "/filter-destinations" => "destinations#filter_destinations"
    get "contact" => "home#contact"
    get "faq" => "home#faq"
    get "contribute" => "home#contribute"
    get "advertise" => "home#advertise"
    get "privacy" => "home#privacy"
    get "careers" => "home#careers"
    get "terms" => "home#terms"
    get "partner_with_us" => "home#partner_with_us"
    post "contact" => "home#contact_form"
    get "/about" => "home#about"
    get "/add-listing" => "home#add_listing"
    post "/add-listing" => "home#save_listing"
    get "/report-spam" => "home#report_spam"
    post "/report-spam" => "home#save_spam"
    get "/report-fraud" => "home#report_fraud"
    post "/report-fraud" => "home#save_fraud"
    post "about" => "home#about"
    post "/share-as-email" => "home#share_as_email"
    get 'wishlists/add' => "wishlists#create"
    get '/customers/:customer_id/wishlists' => "wishlists#index"
    get 'recommendations/add' => "recommendations#create"
    get '/customers/:customer_id/recommendations' => "recommendations#index"
    get '/customers/:customer_id/posts' => "customers#posts"
    post '/posts/:id/comment' => "customers#comment"
    get '/posts/:id/show' => "customers#show_post"
    get '/posts/:id/edit' => "customers#edit_post"
    post '/posts/:id/update' => "customers#update_post"
    get '/posts/:id/like' => "customers#like"
    get '/posts/:id/remove' => "customers#remove_post"
    get '/customers/:customer_id/gallery' => "customers#gallery"
    get '/customers/:customer_id/gallery/:country' => "customers#gallery_by_country"
    get '/customers/:customer_id/followings' => "customers#followings"
    get '/customers/:customer_id/followers' => "customers#followers"
    get "customers/accept_as_public_traveller" => "customers#update_visibility"
    get "/customers/create-post" => "customers#create_post"
    post "/customers/create-post" => "customers#save_post"
    get "/recommendation" => "customers#recommendation"
    get '/wishlists/auth' => "wishlists#index"
    get '/checkins/auth' => "checkins#index"
    get '/recommendation/auth' => "recommendations#index"
    delete 'customers/:customer_id/wishlists/:id' => "wishlists#destroy"
    delete 'customers/:customer_id/recommendations/:id' => "recommendations#destroy"
    get 'checkins/add' => "checkins#create"
    get 'customers/:customer_id/checkins' => "checkins#index"
    delete 'customers/:customer_id/checkins/:id' => "checkins#destroy"
    get '/terms' => "admins#terms"
    get '/faq' => "admins#faq"
    get '/careers' => "admins#careers"
    get '/privacy' => "admins#privacy"
    get '/about' => "admins#about_us"
    get '/terms/edit' => "admins#edit_terms"
    get '/faq/edit' => "admins#edit_faq"
    get '/careers/edit' => "admins#edit_careers"
    get '/privacy/edit' => "admins#edit_privacy"
    get '/about/edit' => "admins#edit_about_us"
    post '/terms/edit' => "admins#update_terms"
    post '/faq/edit' => "admins#update_faq"
    post '/careers/edit' => "admins#update_careers"
    post '/privacy/edit' => "admins#update_privacy"
    post '/about/edit' => "admins#update_about_us"
    get "/change-status" => "customers#change_status"
    post "/change-status" => "customers#update_status"

    resources :destinations do
      get "traveller_images"
      resources :flights do
        resources :flight_facilities
      end
      resources :hotels do
        resource :hotel_facilities
        resource :mores
      end
      resources :attractions
      resources :events
    end

    patch "/update_d_rating/:id" => "ratings#update_destination"
    patch "update_f_rating/:id" => "ratings#update_flight"

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show, :all_index]
  before_action :set_attraction, only: [:edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @dest = Destination.includes(:attractions).where(slug: params["slug"]).first
    if @dest.present?
      @attractions = @dest.attractions.all
    else
      return redirect_to "/attractions"
    end
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
    @attraction = Attraction.where(slug: params[:attraction_slug]).first
    if @attraction.present?
      @destination = @attraction.destination
    else
      return redirect_to "/attractions"
    end
  end

  def all_index
    @attractions = Attraction.all
  end

  # GET /attractions/new
  def new
    @is_with_location = params["add_location"].present? ? true : false
    unless @is_with_location
      dest = Destination.where(id: params["destination_id"]).first
      @attraction = dest.attractions.new
      # add_breadcrumb "New Flights", new_destination_atrraction_path(params["destination_id"]), "new Flights"
    else
      @attraction = Attraction.new
    end
  end

  # GET /attractions/1/edit
  def edit
    dest = Destination.where(id: params["destination_id"]).first
    unless dest.attractions.blank?
      @attraction = dest.attractions.find(params["id"])
    end
  end

  # POST /attractions
  # POST /attractions.json
  def create

    @add_location = params["add_location"].present? ? true : false

    unless @add_location
      dest = Destination.where(id: params["destination_id"]).first
    else
      if params["locations"].present?
        if params["locations"]["country"].present? && params["locations"]["state"].present? && params["locations"]["cities"].present? && params["locations"]["name"].present?
          dest = AppUtils.get_location_details_for_flight_or_hotel(params["locations"]).first
        else
          redirect_to "/add_attractions/?add_location=true", :flash=> {:error=>"Enter valid location"}
        end
      else
        redirect_to "/add_attractions/?add_location=true", :flash=> {:error=>"Enter valid location"}
      end
    end

    @attraction = dest.attractions.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        DynamicJob.perform_async
        format.html { redirect_to "/attractions", notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    dest = Destination.where(id: params["destination_id"]).first
    @attraction = dest.attractions.find(params["id"])
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to "/attractions", notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :addr_no, :addr_street, :addr_city, :image, :main_image, :price, :destination_id, :slug)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%
  unless @is_with_location
    url_path = params[:action] == "new" ? "/destinations/#{params['destination_id']}/#{params['destination_name']}/attractions" : "/destinations/#{params['destination_id']}/#{params['destination_name']}/attractions/#{params['id']}"
  else
    url_path = "/destinations/1/bangalore/attractions"
  end
%>

<%= form_for(@attraction, url: url_path, :html => {:multipart => true}) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-item">
    <%= f.label "Name of the attraction" %>
    <%= f.text_field :name %>
  </div>

  <div class="form-item">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <% unless @is_with_location %>
    <%= f.hidden_field :destination_id, :value=>"#{params["destination_id"]}" %>
  <% end %>

  <% if @is_with_location %>
    <div class="form-item">
      <%= label_tag :locations_name, "Attraction Location" %>
      <%= text_field :locations, :name, class: "form-control" %>
    </div>
    <div class="form-item">
      <%= label_tag :locations_country %>
      <%= select :locations, :country, AppUtils.country_list, {:selected=> "", :prompt=> "Select country"  }, class: "form-control" %>
    </div>
    <div class="form-item">
      <%= label_tag :locations_state %>
      <%= select :locations, :state, "", {:selected=> "", :prompt=> "Select state" }, class: "form-control" %>
    </div>

    <div class="form-item">
      <%= label_tag :locations_cities %>
      <%= select :locations, :cities, "", {:selected=> "", :prompt=> "Select city" }, class: "form-control" %>
    </div>
    <input type="hidden" name="add_location" value="true">
  <% end %>

   <div class="form-item">
    <%= f.label "Address" %>
    <%= f.text_field :addr_no %>
  </div>
   <div class="form-item">
    <%= f.label "Street" %>
    <%= f.text_field :addr_street %>
  </div>
  
  <%= f.hidden_field :main_image %>
  <%= hidden_field_tag :main_old_image, @attraction.main_image if @attraction.present? %>
  <%= f.hidden_field :image, name: "attraction[image]" %>
  <div class="form-item" >
    <button type="button" class="btn btn-primary " data-toggle="modal" data-target=".image-modal-lg">Upload images</button>
  </div>
  <!--  <div class="form-item">
   <%#= f.label :price %>
   <%#= f.number_field :price %>
    </div> -->
   <!-- <div class="form-item">
    <%#= f.label :destination_id %>
    <%#= f.text_field :destination_id %>
     </div> -->
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render :partial=> "common/images_multiple", :locals=>{:single_id=> "attraction_main_image", :single_old=> "main_old_image", :multiple_id=>"attraction_image", :action_param=> "attraction_id=#{@attraction.present? ? @attraction.id : "" }" } %>

<% if @is_with_location %>
  <script>
    (function($){
      $("#locations_country, #locations_cities, #locations_state").chosen();
      $("#locations_country").on("change", function(e){
        e.preventDefault();
        $.ajax({
              url: '/get_states',
              dataType: 'json',
              data: {country: $(this).val()}
            })
            .done(function(result) {
              if (result.length > 0){
                states = "";
                $.each(result, function(index, data){
                  states += "<option value='"+data[1]+"'>"+data[0]+"</option>";
                });
                $("#locations_state").html(states);
                $("#locations_state").trigger("chosen:updated");
              }
            })
      });

    $("#locations_state").on("change", function(e){
      e.preventDefault();
      $.ajax({
            url: '/get_cities',
            dataType: 'json',
            data: {state: $(this).val(), country: $("#locations_country").val()}
          })
          .done(function(result) {
            if (result.length > 0){
              cities = "";
              $.each(result, function(index, data){
                cities += "<option value='"+data[1]+"'>"+data[0]+"</option>";
              });
              $("#locations_cities").html(cities);
              $("#locations_cities").trigger("chosen:updated");
            }
          })
      });

    })(jQuery);


  </script>
<% end %>

app/views/attractions/all_index.html.erb
<section class="awe-parallax page-heading-attraction">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="blog-heading-content text-uppercase"><h2>Attractions</h2></div>
  </div>
</section>

<section class="your-destinations-section-demo">
  <div class="container">
    <div class="col-md-8">
      <div class="your-destinations">
        <div class="your-destionations__top">
          <% if admin_signed_in? %>
            <%= link_to '<i class="fa fa-plus"></i> Add New Attraction'.html_safe, "/add_attractions?add_location=true", :class=>"btn btn-primary" %>
          <% end %>
          <div class="your-destinations__bar">
            <div class="order">
              <select class="orderby awe-select">
                <option>Best Match</option>
              </select>
            </div>
          </div>
        </div>
        <div class="destination-list__content">
          <%
            dest_hash = AppUtils.destinations_mapping
          %>
          <% unless @attractions.nil? || @attractions.blank? %>
              <% @attractions.each do |attraction| %>
                  <div class="destinations-item">
                    <div class="col-md-4 p0">
                      <%
                        img_path = Attraction.get_desination_image_by_main_image_or_secondary(attraction)
                      %>
                      <div class="media-img"> <a href="/attractions/<%= attraction.destination.slug %>/<%= attraction.slug %>"><img src="<%= img_path %>" alt=" <%= attraction.name %>"></a></div>
                      <div class="item-cat">
                        <ul>
                          <li><a href="/destinations/<%= attraction.destination.id %>/<%= attraction.destination.destination_name %>/attractions/<%= attraction.id %>/<%= attraction.name %>"><%= attraction.destination.destination_name %></a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="item-body col-md-8">
                      <div class="item-title">
                        <div class="date">Created on <%= attraction.updated_at.to_date.strftime("%A %d, %Y") %>
                        </div>
                        <h2>
                          <a href="/attractions/<%= attraction.destination.slug %>/<%= attraction.slug %>">
                            <%= attraction.name %>
                          </a>
                        </h2>
                      </div>
                     <!--  <div class="item-description">
                       <div>
                         <%#= Nokogiri::HTML(attraction.about).text.truncate(100) %>
                       </div>
                     </div> -->
                      <div class="item-footer">
                        <div class="date-time">
                          <i class="fa fa-map-marker"></i> <%= attraction.addr_no %>, <%= attraction.addr_street %><br> <%= attraction.addr_city %>
                        </div>
                      </div>
                      <div class="dropdown dest_drop">
                        <a id="dLabel" href="javascript:void(0)" data-toggle="dropdown" role="button" aria-haspopup="true">
                          <i class="fa fa-ellipsis-v"></i>
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                          <li><a href="/attractions/<%= attraction.destination.slug %>/<%= attraction.slug %>"><i class="fa fa-eye"></i>&nbsp;&nbsp;View Place</a></li>
                          <% if admin_signed_in? %>
                            <li><a href="/destinations/<%= attraction.destination.id %>/<%= attraction.destination.destination_name %>/attractions/<%= attraction.id %>/edit"><i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit</a></li>
                            <li><%= link_to '<i class="fa fa-trash"></i>&nbsp;&nbsp;Delete'.html_safe, "/destinations/#{attraction.destination.id}/#{attraction.destination.destination_name}/attractions/#{attraction.id}", method: :delete, data: { confirm: 'Are you sure?' }%></li>
                          <% end %>
                        </ul>
                      </div>
                    </div>
                  </div>

                   
              <% end %>
          <% else %>
              <div >
                <h4>There is no attractions for this destination! Create new attraction details!</h4>
              </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">

    </div>
  </div>
</section>

<!-- 
<table>

  <tbody>
    <%# @attractions.each do |attraction| %>
      <tr>
        <td><%#= attraction.name %></td>
        <td><%#= attraction.addr_no %></td>
        <td><%#= attraction.addr_street %></td>
        <td><%#= attraction.addr_city %></td>
        <td><%#= attraction.image %></td>
        <td><%#= attraction.price %></td>
        <td><%#= attraction.destination %></td>
        <td><%#= link_to 'Show', destination_attraction_path(params["destination_id"], attraction.id)  %></td>
        <td><%#= link_to 'Edit', edit_destination_attraction_path(params["destination_id"], attraction.id)  %></td>
        <td><%#= link_to 'Destroy', destination_attraction_path(params["destination_id"], attraction.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>
 -->


<%#= link_to 'New Attraction', new_destination_attraction_path %>

app/views/attractions/edit.html.erb
<section class="awe-parallax new-flight-page">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="login-register-page__content">
      <div class="content-title">
        <h2 class="text-primary">Edit Attraction</h2>
      </div>
      <%= render 'form' %>
      <div class="back-btn">
        <%= link_to 'Show', "/attractions/#{@attraction.destination.slug}/#{@attraction.slug}", :class=>"btn btn-primary" %> &nbsp;&nbsp;
        <%= link_to '<< Back', "/attractions/#{@attraction.destination.slug}", :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</section>

app/views/attractions/index.html.erb
<%= stylesheet_link_tag    "v2/all", media: "all", "data-turbolinks-track" => true %>
<section class="traveler-banner mt-0">
  <div class="py-4">
    <div class="container py-4">
      <div class="block-17 my-1 col-9 offset-3 mx-auto">
        <h2 class="text-center">Attractions</h2>
      </div>
    </div>
  </div>
 </section>

<!-- 
<table>

  <tbody>
    <%# @attractions.each do |attraction| %>
      <tr>
        <td><%#= attraction.name %></td>
        <td><%#= attraction.addr_no %></td>
        <td><%#= attraction.addr_street %></td>
        <td><%#= attraction.addr_city %></td>
        <td><%#= attraction.image %></td>
        <td><%#= attraction.price %></td>
        <td><%#= attraction.destination %></td>
        <td><%#= link_to 'Show', destination_attraction_path(params["destination_id"], attraction.id)  %></td>
        <td><%#= link_to 'Edit', edit_destination_attraction_path(params["destination_id"], attraction.id)  %></td>
        <td><%#= link_to 'Destroy', destination_attraction_path(params["destination_id"], attraction.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>
 -->


<%#= link_to 'New Attraction', new_destination_attraction_path %>
<section class="ftco-sectioninner ftco-destination">
<% if admin_signed_in? %>
            <%= link_to '<i class="fa fa-plus"></i> Add New Attraction'.html_safe, "/destinations/#{@dest.id}/#{@dest.destination_name}/attractions/new", :class=>"btn btn-primary" %>
          <% end %>  
<div class="container">
    <div class="row">
    
      <%  
        dest_hash = AppUtils.destinations_mapping
      %>
      <% unless @attractions.nil? || @attractions.blank? %>
        <% @attractions.each do |attraction| %>
          <div class="attractionsmain col-lg-3 col-md-4 col-sm-12 col-xs-12">
            <div class="attractions">
            <%
              img_path = Attraction.get_desination_image_by_main_image_or_secondary(attraction)
            %>
              <a href="/attractions/<%= attraction.destination.slug %>/<%= attraction.slug %>" class="img d-flex justify-content-center align-items-center">
                <img src="<%= img_path %>" alt=" <%= attraction.name %>"/>
                <div class="icon d-flex justify-content-center align-items-center">
                  <span class="fa fa-search"></span>
                </div>
              </a>
            </div>
            <ul>
              <li class="attr_head"><i class="fa fa-map-marker"></i> <%= attraction.name %></li>
              <li class="attr_link"><a href="#">Reviews</a> <a href="#">Photos</a></li>
            </ul>
          </div>
          <% end %>
          <% else %>
          <div >
            <h4>There is no attractions for this destination! Create new attraction details!</h4>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/attractions/new.html.erb
<section class="awe-parallax register-page-demo">
  <div class="awe-overlay"></div>
  <div class="container">
    <div class="login-register-page__content">
      <div class="content-title">
        <h2 class="text-primary">New Attraction</h2>
      </div>
		<%= render 'form' %>
		<div class="">
		<%#= link_to '<< Back', destination_attractions_path, :class=>"btn login-register-link" %>
      </div>
		</div>
	</div>
</section>